version: '3.2'

volumes:
  mongodb-data:
  pg-data:

services:
  phpcrystal-php:
    build: .
    container_name: "php.phpcrystal"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - XDEBUG_CONFIG='idekey=xdebug; xdebug.remote_host=192.168.0.115'
      - MONGODB_HOST=phpcrystal-mongodb

  phpcrystal-nginx:
    build: ./config/docker/nginx/dev
    container_name: "nginx.phpcrystal"
    ports:
      - 60000:80
    volumes:
      - type: bind
        source: ./
        target: /var/www/html

  phpcrystal-mongodb:
    image: mongo:3.4.1
    container_name: "mongodb.phpcrystal"
    volumes:
      - mongodb-data:/data/db

  phpcrystal-postgres:
    image: postgres:10.3-alpine
    container_name: "postgres.phpcrystal"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=phpcrystal_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pg-data:/var/lib/postgresql/data

  phpcrystal-mongodb-data:
    image: alpine
    container_name: "data.mongodb.phpcrystal"
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
    command: "true"

  phpcrystal-redis:
    image: redis:3.2.7-alpine
    container_name: "redis.phpcrystal"
