version: '2'
services:
  phpcrystal-php:
    build: .
    container_name: "php.phpcrystal"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    environment:
      - XDEBUG_CONFIG='idekey=xdebug; xdebug.remote_host=192.168.0.115'
      - MONGODB_HOST=phpcrystal-mongodb

  phpcrystal-nginx:
    build: ./config/docker/nginx/dev
    container_name: "nginx.phpcrystal"
    ports:
      - 60000:80
    volumes_from:
      - phpcrystal-php:ro

  phpcrystal-mongodb:
    image: mongo:3.4.1
    container_name: "mongodb.phpcrystal"
    volumes_from:
      - phpcrystal-mongodb-data

  phpcrystal-mongodb-data:
    image: alpine
    container_name: "data.mongodb.phpcrystal"
    volumes:
      - /data/db
    command: "true"

  phpcrystal-redis:
    image: redis:3.2.7-alpine
    container_name: "redis.phpcrystal"
